import type { Position } from '@/lib/types'
import { currency, number, percent } from '@/lib/formatters'
import { cn } from '@/lib/utils'
import { Badge } from '@/components/ui/badge'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'

export function PositionsView({ positions }: { positions: Position[] }) { return <><div className="hidden overflow-hidden rounded-xl border bg-card md:block"><Table><TableHeader><TableRow><TableHead>Ativo</TableHead><TableHead>Qtd.</TableHead><TableHead>Preço médio</TableHead><TableHead>Preço atual</TableHead><TableHead>Mercado</TableHead><TableHead>Resultado</TableHead><TableHead className="text-right">Retorno</TableHead></TableRow></TableHeader><TableBody>{positions.map(p => <TableRow key={p.asset.id}><TableCell><div className="font-medium">{p.asset.name}</div><div className="font-mono text-xs text-muted-foreground">{p.asset.ticker}</div></TableCell><TableCell>{number(p.quantity)}</TableCell><TableCell>{currency(p.average_price)}</TableCell><TableCell>{currency(p.current_price)}</TableCell><TableCell>{currency(p.market_value)}</TableCell><TableCell className={cn('font-medium', p.pnl >= 0 ? 'text-positive' : 'text-destructive')}>{currency(p.pnl)}</TableCell><TableCell className="text-right"><Badge variant={p.return_percentage >= 0 ? 'default' : 'destructive'}>{percent(p.return_percentage)}</Badge></TableCell></TableRow>)}</TableBody></Table></div><div className="flex flex-col gap-3 md:hidden">{positions.map(p => <Card key={p.asset.id}><CardHeader><CardTitle className="flex items-center justify-between gap-3"><span>{p.asset.name}</span><Badge variant="secondary">{p.asset.ticker}</Badge></CardTitle></CardHeader><CardContent className="grid grid-cols-2 gap-4 text-sm"><Metric label="Quantidade" value={number(p.quantity)}/><Metric label="Preço médio" value={currency(p.average_price)}/><Metric label="Preço atual" value={currency(p.current_price)}/><Metric label="Valor de mercado" value={currency(p.market_value)}/><Metric label="Resultado" value={currency(p.pnl)} signed={p.pnl}/><Metric label="Rentabilidade" value={percent(p.return_percentage)} signed={p.return_percentage}/></CardContent></Card>)}</div></> }
function Metric({ label, value, signed }: { label: string; value: string; signed?: number }) { return <div><p className="text-xs text-muted-foreground">{label}</p><p className={cn('mt-1 font-medium', signed !== undefined && (signed >= 0 ? 'text-positive' : 'text-destructive'))}>{value}</p></div> }
